name: sciware-python-packaging-examples
channels:
  - conda-forge
  - defaults
dependencies:
  # for the notebook
  - python==3.11
  - jupyterlab
  - emcee
  - autograd
  - tqdm
  - matplotlib
  # these three will be dependencies of our new package
  # so future users wouldn't need to install them independently
  - scipy
  - numpy
  - celerite
  # for help packaging
  - pip
  - build
  - twine # for uploading to PyPI
